excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://edenpark.github.io
title: Awesome
email: edenpark.dev@gmail.com
author: Eden
description: My awesome new site
paginate: 3
google_analytics: 