excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://edenpark.github.io
title: </>
email: edenpark.dev@gmail.com
author: Eden Park
description: Welcome to my world.
paginate: 3
google_analytics: UA-78693202-1
